# Generated by Django 4.1.4 on 2022-12-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('descripcionPerfil', models.CharField(max_length=100)),
                ('Birthday', models.CharField(max_length=100)),
                ('Website', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('freelance', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'About me',
                'verbose_name_plural': 'About me',
            },
        ),
    ]
